[theme]
# Primary accent for interactive elements
primaryColor = '#0A21C0'

# Background color for the main content area
backgroundColor = '#050A44'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#141619'

# Color used for almost all text
textColor = '#86C232'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "Rubik"
font = "Rubik"
